# **Task-03 Sales Dataset Analysis:**

## Import Libraries:

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
print("NumPy Version:", np.__version__)
print("Pandas Version:", pd.__version__)

NumPy Version: 2.1.3
Pandas Version: 2.2.3

## Sales Dataset:

### Loading the dataset:
Use encoding='cp1252' because our csv hasnot some characters of UTF-8 format.
By default, Pandas uses UTF-8 encoding when reading CSV files.

However, some CSV files are saved using different character encodings, such as Windows-1252 (also called cp1252).

In [ ]:
df = pd.read_csv('/content/Sample_Superstore.csv', encoding='cp1252')

### Explore the Dataset:

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

###Check Dimensions:
We use shape for it. It returns the dimensions of a DataFrame.
It tells (number_of_rows, number_of_columns)

In [ ]:
df.shape

(9994, 21)

### Check Names of Columns:

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

### Check the DataTypes:
It tells us:
- Number of entries.
- Column names.
- Non-null values.
- Data types.
- Memory usage.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

## Data Cleaning and Quality Check:

### Check Missing Values:

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

### Check Duplicated Records(rows):

In [ ]:
df.duplicated().sum()

np.int64(0)

### Overview of Dataset:
This generates basic statistical information for numerical columns.

It includes:
count-Number of non-missing values,

*   count-Number of non-missing values
*   mean-Average


*   std-Standard deviation
*   min-Minimum value

*   25%-First quartile(Q1)
*   50%-Median(Q2)


*   75%-Third quartile(Q3)
*   max-Maximum value

In [ ]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

## Data Filtering:
Filtering means selecting only those records that satisfy a particular condition.

### Filter High Sales Values
Sales greater than 500 Rs

In [ ]:
high_sales = df[df['Sales'] > 500]

high_sales.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
11,12,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568

In [ ]:
len(high_sales)

1162

In [ ]:
(len(high_sales) / len(df)) * 100

11.626976185711428

### Filter loss-making sales:
To find Sales less than 0 means negative ones to find the loss making sales.

In [ ]:
loss_records = df[df['Profit'] < 0]

loss_records.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
14,15,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580
15,16,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160
23,24,US-2017-156909,7/16/2017,7/18/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0.30,-1.0196
27,28,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522

In [ ]:
len(loss_records)

1871

In [ ]:
(len(loss_records) / len(df)) * 100

18.721232739643785

## Data Sorting:
Sorting arranges records in a particular order.

### Sorting Sales Records:
We sort records from high to low(dec) sales records.

In [ ]:
top_sales = df.sort_values(by='Sales', ascending=False)

top_sales.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
2623,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856

### Sort by Profit:
Sort records who has highest profits to lower profits.

In [29]:
top_profit = df.sort_values(by='Profit', ascending=False)

top_profit.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.95,5,0.0,8399.9760
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.96,4,0.0,6719.9808
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.97,3,0.0,5039.9856
9039,9040,CA-2016-117121,12/17/2016,12/21/2016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.74,13,0.0,4946.3700
4098,4099,CA-2014-116904,9/23/2014,9/28/2014,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.95,5,0.0,4630.4755

## Statistical Analysis:

### Calculate Average Sales:
mean() calculates the arithmetic average.

Formula:
Mean = {Sum of all values}\{Number of values}}

In [30]:
average_sales = df['Sales'].mean()

print("Average Sales:", average_sales)

Average Sales: 229.85800083049833

### Calculate Median Sales:
Median is the middle value when all values are arranged in ascending order.

In [31]:
median_sales = df['Sales'].median()

print("Median Sales:", median_sales)

Median Sales: 54.489999999999995

### Calculate Standard Devision:
Standard Deviation (STD) tells us how spread out the values are from their mean.

#### Sales SD:

In [32]:
sales_std = df['Sales'].std()

print("Sales Standard Deviation:", sales_std)

Sales Standard Deviation: 623.2451005086818

#### Profits SD:

In [33]:
profit_std = df['Profit'].std()

print("Profit Standard Deviation:", profit_std)

Profit Standard Deviation: 234.26010769095757

In [34]:
average_quantity = np.mean(df['Quantity'])

print("Average Quantity:", average_quantity)

Average Quantity: 3.789573744246548

## Category-wise Analysis:

In [35]:
category_analysis = df.groupby('Category')[['Sales', 'Profit']].sum()

category_analysis

                       Sales       Profit
Category
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008
Technology       836154.0330  145454.9481

### Category-wise Findings

1. Technology generated the highest total sales (836,154.03) and the highest total profit (145,454.95).

2. Furniture generated 741,999.80 in sales but only 18,451.27 in profit, showing a relatively small profit compared with its sales.

3. Office Supplies generated lower sales than Furniture but significantly higher profit (122,490.80 compared with 18,451.27).

## Region-wise Analysis:

In [36]:
region_analysis = df.groupby('Region')[['Sales', 'Profit']].sum()

region_analysis

               Sales       Profit
Region
Central  501239.8908   39706.3625
East     678781.2400   91522.7800
South    391721.9050   46749.4303
West     725457.8245  108418.4489

### Region-wise Findings

1. The West region generated the highest sales (725,457.82) and the highest profit (108,418.45).

2. The South region recorded the lowest sales (391,721.91).

3. The Central region generated the lowest total profit (39,706.36), despite having higher sales than the South region.

## Sub Category-wise Profit Analysis:

In [37]:
subcategory_analysis = df.groupby('Sub-Category')[['Sales', 'Profit']].sum()

subcategory_analysis = subcategory_analysis.sort_values(
    by='Profit',
    ascending=False
)

subcategory_analysis

                    Sales      Profit
Sub-Category
Copiers       149528.0300  55617.8249
Phones        330007.0540  44515.7306
Accessories   167380.3180  41936.6357
Paper          78479.2060  34053.5693
Binders       203412.7330  30221.7633
Chairs        328449.1030  26590.1663
Storage       223843.6080  21278.8264
Appliances    107532.1610  18138.0054
Furnishings    91705.1640  13059.1436
Envelopes      16476.4020   6964.1767
Art            27118.7920   6527.7870
Labels         12486.3120   5546.2540
Machines      189238.6310   3384.7569
Fasteners       3024.2800    949.5182
Supplies       46673.5380  -1189.0995
Bookcases     114879.9963  -3472.5560
Tables        206965.5320 -17725.4811

### Sub-Category-wise Findings

1. Copiers generated the highest total profit (55,617.82), even though their sales were lower than Phones and Chairs.

2. Phones recorded the highest sales (330,007.05), but Copiers generated higher profit.

3. Tables recorded the largest total loss (-17,725.48), despite generating 206,965.53 in sales.

4. Bookcases (-3,472.56) and Supplies (-1,189.10) also recorded negative total profits.

5. Out of 17 sub-categories, 3 recorded negative total profits.

## Discount and Profit Analysis:
To investigate does a higher discount correspond to lower profit in this dataset?

In [38]:
discount_analysis = df.groupby('Discount').agg(
    Total_Records=('Profit', 'count'),
    Average_Profit=('Profit', 'mean'),
    Total_Profit=('Profit', 'sum')
)

discount_analysis

          Total_Records  Average_Profit  Total_Profit
Discount
0.00               4798       66.900292   320987.6032
0.10                 94       96.055074     9029.1770
0.15                 52       27.288298     1418.9915
0.20               3657       24.702572    90337.3060
0.30                227      -45.679636   -10369.2774
0.32                 27      -88.560656    -2391.1377
0.40                206     -111.927429   -23057.0504
0.45                 11     -226.646464    -2493.1111
0.50                 66     -310.703456   -20506.4281
0.60                138      -43.077212    -5944.6552
0.70                418      -95.874060   -40075.3569
0.80                300     -101.796797   -30539.0392

### Discount and Profit Findings

1. Records with 0% discount generated the highest total profit (320,987.60).

2. The 10% discount level recorded the highest average profit (96.06).

3. All discount levels from 30% to 80% recorded negative average profits.

4. The 50% discount level had the lowest average profit (-310.70).

5. The 70% discount level generated the largest total loss (-40,075.36).

6. The dataset shows an association between higher discount levels and lower profitability. However, this does not establish that discounts alone cause losses.

## Customer Segment Analysis
Now let's analyze the three customer segments:
- Consumer
- Corporate
- Home Office
We want to know which customer segment contributes the most sales and profit.

In [39]:
segment_analysis = df.groupby('Segment').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Average_Sales=('Sales', 'mean'),
    Average_Profit=('Profit', 'mean')
)

segment_analysis

              Total_Sales  Total_Profit  Average_Sales  Average_Profit
Segment
Consumer     1.161401e+06   134119.2092     223.733644       25.836873
Corporate    7.061464e+05    91979.1340     233.823300       30.456667
Home Office  4.296531e+05    60298.6785     240.972041       33.818664

### Customer Segment Findings

1. The Consumer segment generated the highest total sales (1,161,401.35) and total profit (134,119.21).

2. The Home Office segment recorded the highest average sales per record (240.97).

3. The Home Office segment also achieved the highest average profit per record (33.82).

4. Although Consumer leads in total profit, Home Office performs better in average profit per record.

## Year-wise Sales and Profit Analysis
To explore how business performance changes over time.

To convert Order date columns to Pandas datetme format:

In [40]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

df['Order Date'].dtype

dtype('<M8[ns]')

To create a new column called Year from Order Date.

In [41]:
df['Year'] = df['Order Date'].dt.year

df[['Order Date', 'Year']].head()

  Order Date  Year
0 2016-11-08  2016
1 2016-11-08  2016
2 2016-06-12  2016
3 2015-10-11  2015
4 2015-10-11  2015

In [42]:
yearly_analysis = df.groupby('Year').agg(
    Total_Sales=('Sales', 'sum'),
    Total_Profit=('Profit', 'sum'),
    Average_Sales=('Sales', 'mean'),
    Average_Profit=('Profit', 'mean')
)

yearly_analysis

      Total_Sales  Total_Profit  Average_Sales  Average_Profit
Year
2014  484247.4981    49543.9741     242.974159       24.858994
2015  470532.5090    61618.6037     223.849909       29.314274
2016  609205.5980    81795.1743     235.487282       31.617771
2017  733215.2552    93439.2696     221.381418       28.212340

### Year-wise Findings

1. The year 2017 recorded the highest total sales (733,215.26) and total profit (93,439.27).

2. In 2015, total sales decreased compared with 2014, but total profit increased from 49,543.97 to 61,618.60.

3. The year 2016 achieved the highest average profit per record (31.62).

4. Average profit per record decreased from 31.62 in 2016 to 28.21 in 2017, despite an increase in total profit.

## Count Records per Year:
To investigate why 2017 has higher total profit but lower average profit than 2016.

In [43]:
yearly_records = df.groupby('Year').size()

yearly_records

Year
2014    1993
2015    2102
2016    2587
2017    3312
dtype: int64

The number of records increased from 1,993 in 2014 to 3,312 in 2017. Although 2017 achieved the highest total profit, its average profit per record was lower than in 2016.

## Correaltion between profits and Sales:

In [44]:
sales_profit_correlation = df['Sales'].corr(df['Profit'])

print("Sales-Profit Correlation:", sales_profit_correlation)

Sales-Profit Correlation: 0.4790643497377062

### Sales and Profit Correlation

The correlation between Sales and Profit is approximately 0.48, indicating a moderate positive linear relationship. Generally, higher sales tend to be associated with higher profits, but this relationship is not perfect. Some high-sales transactions can still generate losses.